packages:
  - "apps/*"
  - "packages/*"
overrides:
  '@types/node': ^24.0.0
allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  esbuild: false
  msgpackr-extract: false
  prisma: true
  workerd: false
