// Stable, machine-readable identifiers for every error the API can return.
// The frontend maps each code to the text the user sees, so a code must never
// be renamed once released; add a new one instead.
export const ErrorCode = {
  // Generic (derived from the HTTP status when nothing more specific exists)
  BAD_REQUEST: 'BAD_REQUEST',
  REQUEST_VALIDATION_FAILED: 'REQUEST_VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Authentication
  AUTH_CREDENTIALS_REQUIRED: 'AUTH_CREDENTIALS_REQUIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',

  // Tax roll upload (file level)
  TAX_ROLL_FILE_MISSING: 'TAX_ROLL_FILE_MISSING',
  TAX_ROLL_FILE_EXTENSION: 'TAX_ROLL_FILE_EXTENSION',
  TAX_ROLL_FILE_TOO_LARGE: 'TAX_ROLL_FILE_TOO_LARGE',
  TAX_ROLL_FILE_EMPTY: 'TAX_ROLL_FILE_EMPTY',
  TAX_ROLL_NOT_XLSX: 'TAX_ROLL_NOT_XLSX',
  TAX_ROLL_NO_HEADER_ROW: 'TAX_ROLL_NO_HEADER_ROW',
  TAX_ROLL_HEADERS_MISMATCH: 'TAX_ROLL_HEADERS_MISMATCH',
  TAX_ROLL_NO_DATA_ROWS: 'TAX_ROLL_NO_DATA_ROWS',
  TAX_ROLL_UNREADABLE: 'TAX_ROLL_UNREADABLE',
  MUNICIPALITY_NOT_CONFIGURED: 'MUNICIPALITY_NOT_CONFIGURED',

  // Settlements (administrator panel)
  SETTLEMENT_SEARCH_CRITERIA_REQUIRED: 'SETTLEMENT_SEARCH_CRITERIA_REQUIRED',
  SETTLEMENT_NOT_FOUND: 'SETTLEMENT_NOT_FOUND',
  SETTLEMENT_STATUS_INVALID: 'SETTLEMENT_STATUS_INVALID',
  SETTLEMENT_ALREADY_REPLACED: 'SETTLEMENT_ALREADY_REPLACED',

  // Public consultation (taxpayer)
  PUBLIC_QUERY_CRITERIA_REQUIRED: 'PUBLIC_QUERY_CRITERIA_REQUIRED',

  // Liquidation PDF / bulk ZIP generation
  LIQUIDATION_DATA_INCOMPLETE: 'LIQUIDATION_DATA_INCOMPLETE',
  LIQUIDATION_CONCURRENT_GENERATION: 'LIQUIDATION_CONCURRENT_GENERATION',
  PDF_TEMPLATE_UNAVAILABLE: 'PDF_TEMPLATE_UNAVAILABLE',
  PDF_TEMPLATE_INVALID: 'PDF_TEMPLATE_INVALID',
  PDF_CONVERSION_TIMEOUT: 'PDF_CONVERSION_TIMEOUT',
  PDF_CONVERSION_FAILED: 'PDF_CONVERSION_FAILED',
  NO_PENDING_LIQUIDATIONS: 'NO_PENDING_LIQUIDATIONS',
  BULK_LIMIT_EXCEEDED: 'BULK_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

// Codes for row-level problems found while parsing the tax roll. They travel
// inside a successful (201) import response, not as HTTP errors.
export const RowIssueCode = {
  MISSING_CADASTRAL_CODE: 'MISSING_CADASTRAL_CODE',
  INVALID_PERIOD: 'INVALID_PERIOD',
  PERIOD_OUT_OF_RANGE: 'PERIOD_OUT_OF_RANGE',
  MISSING_OWNER_DOCUMENT: 'MISSING_OWNER_DOCUMENT',
  NON_NUMERIC_VALUE: 'NON_NUMERIC_VALUE',
  INVALID_COORDINATE: 'INVALID_COORDINATE',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  MISSING_OWNER: 'MISSING_OWNER',
} as const;

export type RowIssueCode = (typeof RowIssueCode)[keyof typeof RowIssueCode];
